### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by fasteddys** [KorzhCom/Korzh.DbUtils#27]
Hello what is required to support mongoDB.

Also I got some errors when my db had some other types like spatial types, updated types.

While debugging I saw it was missing some [types](https://docs.microsoft.com/en-us/sql/t-sql/data-types/data-types-transact-sql?view=sql-server-ver15)

**Comment by korzh** [comment]
To add support for Mongo (and for any other DB, actually) EasyData needs 2 things:
1. A Mongo specific implementation if `IModelLoader` interface 
2. A descendant of EasyDataManager that will perform the main CRUD operations over Mongo DB.

As for errors when a DB uses some types. Could you please attach an example of `DbContext` definition (or at least a definition of a model class) with those types? And it's better to create a separate issue for this problem.

**Comment by fasteddys** [comment]
thanks.

I just added the types I needed in the list and the error was gone for now.
